### ISSUE TITLE
generate的时候报错了

### ISSUE THREAD

**Issue by natsuboy** [XuanmiaoG/hexo-baidu-url-push#1]
FATAL {
  err: ReferenceError: path is not defined
      at Hexo.<anonymous> (/home/runner/work/website/website/node_modules/hexo-baidu-url-push/index.js:3:40)
      at Hexo.tryCatcher (/home/runner/work/website/website/node_modules/bluebird/js/release/util.js:16:23)
      at Hexo.<anonymous> (/home/runner/work/website/website/node_modules/bluebird/js/release/method.js:15:34)
      at /home/runner/work/website/website/node_modules/hexo/lib/extend/filter.js:67:52
      at tryCatcher (/home/runner/work/website/website/node_modules/bluebird/js/release/util.js:16:23)
      at Object.gotValue (/home/runner/work/website/website/node_modules/bluebird/js/release/reduce.js:166:18)
      at Object.gotAccum (/home/runner/work/website/website/node_modules/bluebird/js/release/reduce.js:155:25)
      at Object.tryCatcher (/home/runner/work/website/website/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/home/runner/work/website/website/node_modules/bluebird/js/release/promise.js:547:31)
      at Promise._settlePromise (/home/runner/work/website/website/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromise0 (/home/runner/work/website/website/node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (/home/runner/work/website/website/node_modules/bluebird/js/release/promise.js:7[29](https://github.com/always0e0w/website/runs/5291340803?check_suite_focus=true#step:6:29):18)
      at _drainQueueStep (/home/runner/work/website/website/node_modules/bluebird/js/release/async.js:93:12)
      at _drainQueue (/home/runner/work/website/website/node_modules/bluebird/js/release/async.js:86:9)
      at Async._drainQueues (/home/runner/work/website/website/node_modules/bluebird/js/release/async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (/home/runner/work/website/website/node_modules/bluebird/js/release/async.js:15:14)
} Something's wrong. Maybe you can find the solution here: %s https://hexo.io/docs/troubleshooting.html
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Process completed with exit code 2.

**Comment by XuanmiaoG** [comment]
[code change](https://github.com/XuanmiaoG/hexo-baidu-url-push/blame/main/index.js)
已复现该问题，版本变动0.1.4 --> 0.1.5 
目前运行 hexo g 已经不会出现报错问题

**Comment by XuanmiaoG** [comment]
the bug has been repaired, sorry for the trouble.https://github.com/XuanmiaoG/hexo-baidu-url-push/issues/1---- 回复的原邮件 ***@***.***>发送日期2022年02月23日 01:13 ***@***.***> ***@***.***>主题[XuanmiaoG/hexo-baidu-url-push] generate的时候报错了 (Issue #1)
FATAL {
err: ReferenceError: path is not defined
at Hexo. (/home/runner/work/website/website/node_modules/hexo-baidu-url-push/index.js:3:40)
at Hexo.tryCatcher (/home/runner/work/website/website/node_modules/bluebird/js/release/util.js:16:23)
at Hexo. (/home/runner/work/website/website/node_modules/bluebird/js/release/method.js:15:34)
at /home/runner/work/website/website/node_modules/hexo/lib/extend/filter.js:67:52
at tryCatcher (/home/runner/work/website/website/node_modules/bluebird/js/release/util.js:16:23)
at Object.gotValue (/home/runner/work/website/website/node_modules/bluebird/js/release/reduce.js:166:18)
at Object.gotAccum (/home/runner/work/website/website/node_modules/bluebird/js/release/reduce.js:155:25)
at Object.tryCatcher (/home/runner/work/website/website/node_modules/bluebird/js/release/util.js:16:23)
at Promise._settlePromiseFromHandler (/home/runner/work/website/website/node_modules/bluebird/js/release/promise.js:547:31)
at Promise._settlePromise (/home/runner/work/website/website/node_modules/bluebird/js/release/promise.js:604:18)
at Promise._settlePromise0 (/home/runner/work/website/website/node_modules/bluebird/js/release/promise.js:649:10)
at Promise._settlePromises (/home/runner/work/website/website/node_modules/bluebird/js/release/promise.js:729:18)
at _drainQueueStep (/home/runner/work/website/website/node_modules/bluebird/js/release/async.js:93:12)
at _drainQueue (/home/runner/work/website/website/node_modules/bluebird/js/release/async.js:86:9)
at Async._drainQueues (/home/runner/work/website/website/node_modules/bluebird/js/release/async.js:102:5)
at Immediate.Async.drainQueues [as _onImmediate] (/home/runner/work/website/website/node_modules/bluebird/js/release/async.js:15:14)
} Something's wrong. Maybe you can find the solution here: %s https://hexo.io/docs/troubleshooting.html
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Process completed with exit code 2.

—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/XuanmiaoG/hexo-baidu-url-push/issues/1",
"url": "https://github.com/XuanmiaoG/hexo-baidu-url-push/issues/1",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
